add find words command
kubokat/gocurse pull request #1
Opened 2023-06-28 17:56 UTC by kubokat

2023-06-29 07:40 UTC, DmitriyVTitov requested changes
Давайте сразу переделаем структуру каталогов.

2023-06-29 07:40 UTC, DmitriyVTitov commented on go.mod
> +module gosearch
Модуль должен быть один на весь курс, а каждое ДЗ в своём каталоге.
https://github.com/thinknetica/go_course_4/blob/master/00-docs/Modules.MD

2023-06-29 08:15 UTC, kubokat commented on go.mod
> +module gosearch
Изменил

2023-07-01 07:20 UTC, DmitriyVTitov approved these changes
Решение не вполне соответствует заданию. Принимаю, но надо поправить.

2023-07-01 07:20 UTC, DmitriyVTitov commented on 02-lession/search/cmd/main.go
> +	}
По заданию это не так )

2023-07-01 07:20 UTC, DmitriyVTitov commented on 02-lession/search/cmd/main.go
> +		}
Не надо везде fatal(). Это не логично да и вообще, лучше не злоупотреблять.

2023-07-01 07:20 UTC, DmitriyVTitov commented on 02-lession/search/cmd/main.go
> +	}
По заданию следует объединить результаты поиска. И только потом искать.

2023-07-02 17:37 UTC, merged