Fix style sintax
kubokat/gocurse pull request #4
Opened 2023-07-12 16:48 UTC by kubokat

2023-07-14 13:19 UTC, DmitriyVTitov requested changes
Мой код - очень плохой, меняйте его радикальней :)

2023-07-14 13:19 UTC, DmitriyVTitov commented on 06-lession/pkg/dst.go
> +*/
> Методы должны возвращать ошибку

Почему вдруг все должны? Скажем, метод сложения двух чисел какую ошибку должен возвращать?

2023-07-14 13:19 UTC, DmitriyVTitov commented on 06-lession/pkg/dst.go
> +	// Во втором условии нет необходимости + переменная не объявленна (объяляем)
Почему вдруг такое при вычислении расстояния? Почему координаты не могут быть отрицательными?

2023-07-14 13:19 UTC, DmitriyVTitov commented on 06-lession/pkg/dst.go
> +func (geom Geom) CalculateDistance() (float64, error) {
Сигнатура функции не понятная. Она ничего не принимает на вход, какие-то побочные эффекты возможны.

2023-07-14 13:19 UTC, DmitriyVTitov commented on 06-lession/pkg/dst.go
> +	return distance, nil
для чего такой очевидный комментарий?

2023-07-16 10:39 UTC, kubokat commented on 06-lession/pkg/dst.go
> +*/
Ок. В следующей версии убрал обработку ошибок за ненадобностью

2023-07-16 10:40 UTC, kubokat commented on 06-lession/pkg/dst.go
> +	return distance, nil
Убрал

2023-07-16 10:40 UTC, kubokat commented on 06-lession/pkg/dst.go
> +	// Во втором условии нет необходимости + переменная не объявленна (объяляем)
>Почему координаты не могут быть отрицательными?

Думал это условие конкретной задачи. Убрал проверку на отрицательность

2023-07-16 10:42 UTC, kubokat commented on 06-lession/pkg/dst.go
> +func (geom Geom) CalculateDistance() (float64, error) {
По сигнатуре не понял. Вроде как нужные поля задают на уровне структуры и этого достаточно

2023-07-18 09:53 UTC, DmitriyVTitov approved these changes

2023-07-18 09:53 UTC, DmitriyVTitov commented on 06-lession/pkg/dst.go
> +}
строки 13 и 15 надо объединить, имя функции сделать покороче, от ООП-подхода избавиться напрочь!

2023-07-22 13:24 UTC, merged